/*
Meteor.subscribe('restaurantCategory');
Meteor.subscribe('restaurantUnit');
Meteor.subscribe('restaurantSubCategory');
Meteor.subscribe('restaurantStaff');
Meteor.subscribe('restaurantCustomer');
Meteor.subscribe('restaurantProduct');
Meteor.subscribe('restaurantSale');
Meteor.subscribe('restaurantSaleDetail');
Meteor.subscribe('restaurantPayment');
Meteor.subscribe('restaurantPurchase');
Meteor.subscribe('restaurantPurchaseDetail');
Meteor.subscribe('restaurantSupplier');
Meteor.subscribe('restaurantStock');
Meteor.subscribe('restaurantExchangeRate');
Meteor.subscribe('restaurantStockHistory');
Meteor.subscribe('restaurantUserStaff');
Meteor.subscribe('images');
Meteor.subscribe('adjustment');*/
Meteor.subscribe('restaurantOwedSale');
